-- MySQL Script generated by MySQL Workbench
-- 02/06/19 22:51:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SisNomina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SisNomina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SisNomina` DEFAULT CHARACTER SET utf8 ;
USE `SisNomina` ;

-- -----------------------------------------------------
-- Table `SisNomina`.`gradoInstruccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`gradoInstruccion` (
  `cod_gradoInstruccion` INT NOT NULL AUTO_INCREMENT,
  `nombre_gradoInstruccion` VARCHAR(45) NOT NULL,
  `desc_gradoInstruccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_gradoInstruccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`escalafon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`escalafon` (
  `cod_escalafon` INT NOT NULL AUTO_INCREMENT,
  `nombre_escalafon` VARCHAR(45) NOT NULL,
  `desc_escalafon` VARCHAR(155) NULL,
  `valorHora_escalafon` FLOAT NOT NULL,
  PRIMARY KEY (`cod_escalafon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`banco` (
  `cod_banco` INT NOT NULL,
  `nombre_banco` VARCHAR(45) NOT NULL,
  `desc_banco` VARCHAR(155) NULL,
  PRIMARY KEY (`cod_banco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`datosBancarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`datosBancarios` (
  `nroCuenta_datosBancarios` VARCHAR(30) NOT NULL,
  `tipoCuenta_datosBancarios` VARCHAR(15) NULL,
  `cod_banco` INT NOT NULL,
  PRIMARY KEY (`nroCuenta_datosBancarios`),
  INDEX `cod_bancos_idx` (`cod_banco` ASC),
  UNIQUE INDEX `nroCuenta_datosBancarios_UNIQUE` (`nroCuenta_datosBancarios` ASC),
  CONSTRAINT `cod_bancos`
    FOREIGN KEY (`cod_banco`)
    REFERENCES `SisNomina`.`banco` (`cod_banco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`estatus` (
  `cod_estatus` INT NOT NULL AUTO_INCREMENT,
  `nombre_estatus` VARCHAR(25) NOT NULL,
  `desc_estatus` VARCHAR(255) NULL,
  PRIMARY KEY (`cod_estatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`modalidad` (
  `cod_modalidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_modalidad` VARCHAR(45) NOT NULL,
  `desc_modalidad` VARCHAR(255) NULL,
  PRIMARY KEY (`cod_modalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`turno` (
  `cod_turno` INT NOT NULL AUTO_INCREMENT,
  `nombre_turno` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`cod_turno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`usuario` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `password_usuario` VARCHAR(45) NOT NULL,
  `nivelAcceso_usuario` VARCHAR(25) NULL,
  PRIMARY KEY (`cod_usuario`),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`sede` (
  `cod_sede` INT NOT NULL AUTO_INCREMENT,
  `nombre_sede` VARCHAR(45) NOT NULL,
  `direccion_sede` VARCHAR(45) NULL,
  `encargado_sede` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`decanato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`decanato` (
  `cod_decanato` INT NOT NULL AUTO_INCREMENT,
  `nombre_decanato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_decanato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`escuela` (
  `cod_escuela` VARCHAR(15) NOT NULL,
  `nombre_escuela` VARCHAR(45) NOT NULL,
  `director_escuela` VARCHAR(45) NOT NULL,
  `cod_decanato` INT NOT NULL,
  INDEX `cod_decanato_idx` (`cod_decanato` ASC),
  PRIMARY KEY (`cod_escuela`),
  CONSTRAINT `cod_decanato`
    FOREIGN KEY (`cod_decanato`)
    REFERENCES `SisNomina`.`decanato` (`cod_decanato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`docente` (
  `ced_docente` VARCHAR(25) NOT NULL,
  `nombres_docente` VARCHAR(75) NOT NULL,
  `apellidos_docente` VARCHAR(75) NOT NULL,
  `telfLocal_docente` VARCHAR(25) NOT NULL,
  `telfMovil_docente` VARCHAR(15) NOT NULL,
  `direccion_docente` VARCHAR(255) NOT NULL,
  `email_docente` VARCHAR(45) NOT NULL,
  `sexo_docente` VARCHAR(25) NOT NULL,
  `fechaNacimiento_docente` DATE NOT NULL,
  `edoCivil_docente` VARCHAR(25) NOT NULL,
  `cargaFamiliar_docente` INT NOT NULL,
  `nroHijos_docente` INT NOT NULL,
  `rif_docente` VARCHAR(25) NOT NULL,
  `fechaIngreso_docente` DATE NOT NULL,
  `cod_gradoInstruccion` INT NOT NULL,
  `cod_escalafon` INT NOT NULL,
  `cod_decanato` INT NOT NULL,
  `nroCuenta_datosBancarios` VARCHAR(30) NULL,
  `cod_estatus` INT NOT NULL,
  `cod_turno` INT NOT NULL,
  PRIMARY KEY (`ced_docente`),
  UNIQUE INDEX `email_docente_UNIQUE` (`email_docente` ASC),
  UNIQUE INDEX `rif_docente_UNIQUE` (`rif_docente` ASC),
  UNIQUE INDEX `ced_docente_UNIQUE` (`ced_docente` ASC),
  INDEX `cod_gradoInstruccion_idx` (`cod_gradoInstruccion` ASC),
  INDEX `cod_escalafon_idx` (`cod_escalafon` ASC),
  INDEX `cod_decanato_idx` (`cod_decanato` ASC),
  INDEX `nroCuenta_datosBancarios_idx` (`nroCuenta_datosBancarios` ASC),
  INDEX `cod_estatus_idx` (`cod_estatus` ASC),
  INDEX `cod_turno_idx` (`cod_turno` ASC),
  CONSTRAINT `cod_gradoInstruccion`
    FOREIGN KEY (`cod_gradoInstruccion`)
    REFERENCES `SisNomina`.`gradoInstruccion` (`cod_gradoInstruccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_escalafon`
    FOREIGN KEY (`cod_escalafon`)
    REFERENCES `SisNomina`.`escalafon` (`cod_escalafon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_decanato`
    FOREIGN KEY (`cod_decanato`)
    REFERENCES `SisNomina`.`decanato` (`cod_decanato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nroCuenta_datosBancarios`
    FOREIGN KEY (`nroCuenta_datosBancarios`)
    REFERENCES `SisNomina`.`datosBancarios` (`nroCuenta_datosBancarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_estatus`
    FOREIGN KEY (`cod_estatus`)
    REFERENCES `SisNomina`.`estatus` (`cod_estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_turno`
    FOREIGN KEY (`cod_turno`)
    REFERENCES `SisNomina`.`turno` (`cod_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`docenteXsede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`docenteXsede` (
  `ced_docente` VARCHAR(25) NULL,
  `cod_sede` INT NULL,
  INDEX `cod_docente_idx` (`ced_docente` ASC),
  INDEX `cod_sede_idx` (`cod_sede` ASC),
  CONSTRAINT `ced_docente`
    FOREIGN KEY (`ced_docente`)
    REFERENCES `SisNomina`.`docente` (`ced_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_sede`
    FOREIGN KEY (`cod_sede`)
    REFERENCES `SisNomina`.`sede` (`cod_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`docenteXmodalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`docenteXmodalidad` (
  `ced_docente` VARCHAR(25) NULL,
  `cod_modalidad` INT NULL,
  INDEX `cod_modalidad2_idx` (`cod_modalidad` ASC),
  INDEX `ced_docente1_idx` (`ced_docente` ASC),
  CONSTRAINT `ced_docente1`
    FOREIGN KEY (`ced_docente`)
    REFERENCES `SisNomina`.`docente` (`ced_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_modalidad1`
    FOREIGN KEY (`cod_modalidad`)
    REFERENCES `SisNomina`.`modalidad` (`cod_modalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SisNomina`.`docenteXescuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SisNomina`.`docenteXescuela` (
  `ced_docente` VARCHAR(25) NULL,
  `cod_escuela` VARCHAR(15) NULL,
  INDEX `ced_docente2_idx` (`ced_docente` ASC),
  INDEX `cod_escuela2_idx` (`cod_escuela` ASC),
  CONSTRAINT `ced_docente2`
    FOREIGN KEY (`ced_docente`)
    REFERENCES `SisNomina`.`docente` (`ced_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_escuela2`
    FOREIGN KEY (`cod_escuela`)
    REFERENCES `SisNomina`.`escuela` (`cod_escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
